/*
 * tMessage.h
 *
 *  Created on: Feb 28, 2023
 *      Author: mszkudli
 */

#pragma once

#include "../../global.h"


/*
 * a frame has been recieved - an event dedicated for serial frame parser
 *
 *  data is always mFrame.MessageType
 */
static const uint8_t MessageType_SerialFrameRecieved = 0;

/*
 * a sensor event
 * this events may be generated by sensors or by sensor hub
 * where sensor hub may generate events for local and remote sensors
 *
 * data - sensor ID
 *
 */
static const uint8_t MessageType_SensorEvent   = 1;
    typedef struct tSensorEvent
    {
    	uint8_t SensorType;
        uint8_t EventType;
        uint8_t dataBlobSize;
        void *pDataBlob;
    };

/* a button event - digital input process */
static const uint8_t MessageType_DigialInputEvent   = 2;
    typedef struct tDigialInputEvent
    {
        uint16_t ShortClick;
        uint16_t LongClick;
        uint16_t DoubleClick;
    };


// NOTE - app specific event types start from 16


class tMessageReciever {
public:
	tMessageReciever()  { pNext = pFirst ; pFirst = this; }
	~tMessageReciever();

	void RegisterMessageType(uint8_t type)   { mMessageMask |= 1 << type ; }
	void UnRegisterMessageType(uint8_t type) { mMessageMask &=  ~(uint32_t)(1 << type); }

	static void Dispatch(uint8_t type, uint16_t data, void *pData);
protected:
	virtual void onMessage(uint8_t type, uint16_t data, void *pData) = 0;
private:
  static tMessageReciever* pFirst;
  tMessageReciever* pNext;

  uint32_t mMessageMask;	// up to 32 types
};

