manifest:
  defaults:
    remote: szkudlik-homeAutomation

  remotes:
    - name: szkudlik-homeAutomation
      url-base: https://github.com/szkudlik-homeAutomation

  projects:
    - name: ds1820
      path: src/lib/ds1820
      repo-path: Arduino-Temperature-Control-Library
      revision: 7e57cf681b55229c672568d607101c4d25c44d73
      
    - name: ArduinoProcessScheduler    
      path: src/lib/ArduinoProcessScheduler
      repo-path: ArduinoProcessScheduler.git
      revision: 00ee94961e7825fd9d95972458670de8adc1ab0a

    - name: Ethernet
      path: src/lib/Ethernet
      repo-path: EthernetLib.git
      revision: 775fe51397bbff9a259d36fe74d7a2646403421a

    - name: RingBuf
      path: src/lib/RingBuf
      repo-path: ArduinoRingBuffer.git
      revision: 4c3c648fedf5e43b0007fd27cdb3806c5be9e32d

    - name: AceCRC
      path: src/lib/AceCRC
      repo-path: AceCRC.git
      revision: fd967e3a15648ff7dc1ac8191733032314ceec23

    - name: Watchdog
      path: src/lib/Watchdog
      repo-path: Watchdog_lib.git
      revision: f8c11799f7d3b0283bbf330ddb4245c868f729e6
      
    - name: Commander
      path: src/lib/Commander
      repo-path: Commander_lib.git
      revision: 00400242b0a5407d7c02d9568988d1b3200d121d
      
    - name: ArduinoQueue
      path: src/lib/ArduinoQueue
      repo-path: ArduinoQueue_lib
      revision: ec430f73374464b30cc7f69dc5490eb86eff1dc9

    - name: OneWire
      path: src/lib/OneWire
      repo-path: OneWire_lib
      revision: 386a8d0715781fd38a61c7f0a753c2f988a2abca


