manifest:
  defaults:
    remote: szkudlik-homeAutomation

  remotes:
    - name: szkudlik-homeAutomation
      url-base: https://github.com/szkudlik-homeAutomation

  projects:
    - name: ds1820
      path: src/lib/ds1820
      repo-path: Arduino-Temperature-Control-Library
      revision: 7e57cf681b55229c672568d607101c4d25c44d73
      
    - name: ArduinoProcessScheduler    
      path: src/lib/ArduinoProcessScheduler
      repo-path: ArduinoProcessScheduler.git
      revision: 4d50a460d9fbabf550fe90f7084e12fd4ac0b45d

    - name: Ethernet
      path: src/lib/Ethernet
      repo-path: EthernetLib.git
      revision: 54eb50fb74d5e7d7ce6603c7d7b182c7e5a34a42

    - name: RingBuf
      path: src/lib/RingBuf
      repo-path: ArduinoRingBuffer.git
      revision: 4c3c648fedf5e43b0007fd27cdb3806c5be9e32d

    - name: AceCRC
      path: src/lib/AceCRC
      repo-path: AceCRC.git
      revision: fd967e3a15648ff7dc1ac8191733032314ceec23

    - name: Watchdog
      path: src/lib/Watchdog
      repo-path: Watchdog_lib.git
      revision: f8c11799f7d3b0283bbf330ddb4245c868f729e6
      
    - name: Commander
      path: src/lib/Commander
      repo-path: Commander_lib.git
      revision: 502c2b592338c044ba077a458518ffe74ddac6f1
      
    - name: ArduinoQueue
      path: src/lib/ArduinoQueue
      repo-path: ArduinoQueue_lib
      revision: ec430f73374464b30cc7f69dc5490eb86eff1dc9

    - name: OneWire
      path: src/lib/OneWire
      repo-path: OneWire_lib
      revision: 386a8d0715781fd38a61c7f0a753c2f988a2abca

    - name: Wiegand
      path: src/lib/Wiegand
      repo-path: Wiegand-Protocol-Library-for-Arduino.git
      revision: 66a1b619fac1d4de712c340f3cef4b2073b0e996



