manifest:
  defaults:
    remote: szkudlik-homeAutomation

  remotes:
    - name: szkudlik-homeAutomation
      url-base: https://github.com/szkudlik-homeAutomation

  projects:
    - name: ArduinoProcessScheduler    
      path: src/lib/ArduinoProcessScheduler
      repo-path: ArduinoProcessScheduler.git
      revision: 00ee94961e7825fd9d95972458670de8adc1ab0a

    - name: Ethernet
      path: src/lib/Ethernet
      repo-path: EthernetLib.git
      revision: 775fe51397bbff9a259d36fe74d7a2646403421a

    - name: RingBuf
      path: src/lib/RingBuf
      repo-path: ArduinoRingBuffer.git
      revision: 4c3c648fedf5e43b0007fd27cdb3806c5be9e32d

    - name: AceCRC
      path: src/lib/AceCRC
      repo-path: AceCRC.git
      revision: fd967e3a15648ff7dc1ac8191733032314ceec23

    - name: TCP_Communication_lib
      path: src/TCP_Communication_lib
      repo-path: TCP_Communication_lib.git
      revision: d77f8fa6031789e9c35c55c87a63eae79b06ab4b

    - name: TLE8457_serial_lib
      path: src/TLE8457_serial_lib
      repo-path: TLE8457_serial_lib.git
      revision: 004f75db578967880e93749fe4c8e1ae8fe951e4
