manifest:
  defaults:
    remote: szkudlik-homeAutomation

  remotes:
    - name: szkudlik-homeAutomation
      url-base: https://github.com/szkudlik-homeAutomation

  projects:
    - name: ds1820
      path: src/lib/ds1820
      repo-path: Arduino-Temperature-Control-Library
      revision: a03035a85f730a6835019b1bc740caddf285b302
      
    - name: ArduinoProcessScheduler    
      path: src/lib/ArduinoProcessScheduler
      repo-path: ArduinoProcessScheduler.git
      revision: 00ee94961e7825fd9d95972458670de8adc1ab0a

    - name: Ethernet
      path: src/lib/Ethernet
      repo-path: EthernetLib.git
      revision: 521aa9196df9685f7bcf0a8d5cb8f23bbcc4da68

    - name: RingBuf
      path: src/lib/RingBuf
      repo-path: ArduinoRingBuffer.git
      revision: 4c3c648fedf5e43b0007fd27cdb3806c5be9e32d

    - name: AceCRC
      path: src/lib/AceCRC
      repo-path: AceCRC.git
      revision: fd967e3a15648ff7dc1ac8191733032314ceec23

